# Generate expected/*.csv by running all R tasks
# install.packages(c("dplyr","tidyr","lubridate","readr","stringr"))
source("tasks/001_select_filter.R")
source("tasks/002_groupby_aggregate.R")
source("tasks/003_missing_value_handle.R")
source("tasks/004_join_inner_left_right.R")
source("tasks/005_pivot.R")
source("tasks/006_window_function.R")
source("tasks/007_string_handling.R")
source("tasks/008_date_type_handling.R")
source("tasks/009_conditional_column_creation.R")
source("tasks/010_dataframe_calculation_append.R")
cat("All expected/*.csv generated.\\n")
